data = {
    'Friday, September 20': {
        'Cabaret Metro Stage': [
            {
                name: 'WINONA FIGHTER',
                start: '12:45',
                end: '1:15',
                id: 0,
            },
            {
                name: 'THE WARNING',
                start: '1:55',
                end: '2:25',
                id: 1,
            },
            {
                name: 'THE ACES',
                start: '3:05',
                end: '3:35',
                id: 2,
            },
            {
                name: 'HOT MULLIGAN',
                start: '4:15',
                end: '4:55',
                id: 3,
            },
            {
                name: 'SUM 41',
                start: '6:05',
                end: '7:05',
                id: 4,
            },
            {
                name: 'FALL OUT BOY',
                start: '8:15',
                end: '10:00',
                id: 5,
            },
        ],
        'AAA Stage': [
            {
                name: 'ACTION/ADVENTURE',
                start: '12:10',
                end: '12:40',
                id: 6,
            },
            {
                name: 'POLARIS',
                start: '1:20',
                end: '1:50',
                id: 7,
            },
            {
                name: 'POISON THE WELL',
                start: '2:30',
                end: '3:00',
                id: 8,
            },
            {
                name: 'STATE CHAMPS',
                start: '3:40',
                end: '4:10',
                id: 9,
            },
            {
                name: 'NEW FOUND GLORY',
                start: '5:00',
                end: '6:00',
                id: 10,
            },
            {
                name: 'THE OFFSPRING',
                start: '7:10',
                end: '8:10',
                album: 'SMASH',
                id: 11,
            },
        ],
        'NOFX World': [
            {
                name: 'GET DEAD',
                start: '12:00',
                end: '12:30',
                id: 12,
            },
            {
                name: 'THE EXPLOITED',
                start: '1:00',
                end: '130',
                id: 13,
            },
            {
                name: 'THE DEFIANT',
                start: '2:00',
                end: '2:30',
                id: 14,
            },
            {
                name: 'ALL',
                start: '3:00',
                end: '3:30',
                id: 15,
            },
            {
                name: 'FACE TO FACE',
                start: '4:00',
                end: '5:00',
                id: 16,
            },
            {
                name: 'THE LAWRENCE ARMS',
                start: '5:30',
                end: '6:30',
                id: 17,
            },
            {
                name: 'CIRCLE JERKS',
                start: '7:00',
                end: '8:00',
                id: 18,
            },
            {
                name: 'NOFX: A FINAL FAREWELL',
                start: '8:30',
                end: '10:00',
                id: 19,
            },
        ],
        'Rise Stage': [
            {
                name: 'PEOPLE R UGLY',
                start: '1:05',
                end: '1:35',
                id: 20,
            },
            {
                name: 'JHARIAH',
                start: '2:15',
                end: '2:45',
                id: 21,
            },
            {
                name: 'THE CHISEL',
                start: '3:25',
                end: '3:55',
                id: 22,
            },
            {
                name: 'TORNILLO',
                start: '4:45',
                end: '5:25',
                id: 23,
            },
            {
                name: 'CYPRESS HILL',
                start: '6:20',
                end: '7:20',
                id: 24,
            },
            {
                name: 'THE MARLEY BROTHERS PERFORMING BOB MARLEY',
                start: '8:30',
                end: '10:00',
                id: 25,
            },
        ],
        'Radical Stage': [
            {
                name: 'ZHEANI',
                start: '12:30',
                end: '1:00',
                id: 26,
            },
            {
                name: 'HOME FRONT',
                start: '1:40',
                end: '2:10',
                id: 27,
            },
            {
                name: 'SPIRITUAL CRAMP',
                start: '2:50',
                end: '3:20',
                id: 28,
            },
            {
                name: 'DRUG CHURCH',
                start: '4:00',
                end: '4:40',
                id: 29,
            },
            {
                name: 'SOULS OF MISCHIEF',
                start: '5:30',
                end: '6:15',
                id: 30,
            },
            {
                name: 'PUBLIC ENEMY',
                start: '7:25',
                end: '8:25',
                id: 31,
            },
        ],
    },
    'Saturday, September 21': {
        'Cabaret Metro Stage': [
            {
                name: 'VERBÖTEN',
                start: '11:30',
                end: '12:00',
                id: 32,
            },
            {
                name: 'BRUTUS',
                start: '12:35',
                end: '1:05',
                id: 33,
            },
            {
                name: 'BUZZCOCKS',
                start: '1:45',
                end: '2:15',
                id: 34,
            },
            {
                name: 'THE HIVES',
                start: '2:55',
                end: '3:35',
                id: 35,
            },
            {
                name: 'MANCHESTER ORCHESTRA',
                start: '4:25',
                end: '5:25',
                album: 'COPE',
                id: 36,
            },
            {
                name: 'ST. VINCENT',
                start: '6:35',
                end: '7:35',
                id: 37,
            },
            {
                name: 'BECK',
                start: '8:45',
                end: '10:00',
                id: 38,
            },
        ],
        'AAA Stage': [
            {
                name: 'PIXEL GRIP',
                start: '12:00',
                end: '12:30',
                id: 39,
            },
            {
                name: 'PRINCESS GOES',
                start: '1:10',
                end: '1:40',
                id: 40,
            },
            {
                name: 'SIR CHLOE',
                start: '2:20',
                end: '2:50',
                id: 41,
            },
            {
                name: 'HEALTH',
                start: '3:40',
                end: '4:20',
                id: 42,
            },
            {
                name: 'SPOON',
                start: '5:30',
                end: '6:30',
                id: 43,
            },
            {
                name: 'PAVEMENT',
                start: '7:40',
                end: '8:40',
                id: 44,
            },
        ],
        'NOFX World': [
            {
                name: 'URETHANE',
                start: '12:00',
                end: '12:30',
                id: 45,
            },
            {
                name: 'CODEFENDANTS',
                start: '12:50',
                end: '1:20',
                id: 46,
            },
            {
                name: 'THE DEAD MILKMEN',
                start: '1:40',
                end: '2:10',
                id: 47,
            },
            {
                name: 'THE DICKIES',
                start: '2:30',
                end: '3:00',
                id: 48,
            },
            {
                name: 'D.O.A.',
                start: '3:30',
                end: '4:00',
                id: 49,
            },
            {
                name: 'DILLINGER FOUR',
                start: '4:30',
                end: '5:15',
                id: 50,
            },
            {
                name: 'LAGWAGON',
                start: '5:45',
                end: '6:30',
                id: 51,
            },
            {
                name: 'DESCENDENTS',
                start: '7:00',
                end: '8:00',
                id: 52,
            },
            {
                name: 'NOFX: A FINAL FAREWELL',
                start: '8:30',
                end: '10:00',
                id: 53,
            },
        ],
        'Rise Stage': [
            {
                name: 'LIQUID MIKE',
                start: '11:45',
                end: '12:15',
                id: 54,
            },
            {
                name: 'LORD OF THE LOST',
                start: '12:45',
                end: '1:15',
                id: 55,
            },
            {
                name: 'SWEET PILL',
                start: '1:50',
                end: '2:20',
                id: 56,
            },
            {
                name: 'THE ARMED',
                start: '3:00',
                end: '3:30',
                id: 57,
            },
            {
                name: 'SINCERE ENGINEER',
                start: '4:10',
                end: '4:40',
                id: 58,
            },
            {
                name: 'BEACH BUNNY',
                start: '5:30',
                end: '6:10',
                id: 59,
            },
            {
                name: 'LS DUNES',
                start: '7:05',
                end: '7:50',
                id: 60,
            },
            {
                name: 'TAKING BACK SUNDAY',
                start: '9:00',
                end: '10:00',
                id: 61,
            },
        ],
        'Radical Stage': [
            {
                name: 'HEART ATTACK MAN',
                start: '12:15',
                end: '12:45',
                id: 62,
            },
            {
                name: 'JACK KAYS',
                start: '1:15',
                end: '1:45',
                id: 63,
            },
            {
                name: 'RIVAL SONS',
                start: '2:25',
                end: '2:55',
                id: 64,
            },
            {
                name: 'CLUTCH',
                start: '3:35',
                end: '4:05',
                id: 65,
            },
            {
                name: 'BASEMENT',
                start: '4:45',
                end: '5:25',
                id: 66,
            },
            {
                name: 'WAXAHATCHEE',
                start: '6:15',
                end: '7:00',
                id: 67,
            },
            {
                name: 'BRIGHT EYES',
                start: '7:55',
                end: '8:55',
                id: 68,
            },
        ],
    },
    'Sunday, September 22': {
        'Cabaret Metro Stage': [
            {
                name: 'NEKROGOBLIKON',
                start: '12:10',
                end: '12:40',
                id: 69,
            },
            {
                name: 'SPRINTS',
                start: '1:20',
                end: '1:50',
                id: 70,
            },
            {
                name: 'GEL',
                start: '2:30',
                end: '3:00',
                id: 71,
            },
            {
                name: 'MASTODON',
                start: '3:50.',
                end: '4:50',
                album: 'LEVIATHAN',
                id: 72,
            },
            {
                name: 'LAMB OF GOD',
                start: '6:00',
                end: '7:00',
                id: 73,
            },
            {
                name: 'SLAYER',
                start: '8:15',
                end: '10:00',
                id: 74,
            },
        ],
        'AAA Stage': [
            {
                name: 'HUGE EUGE',
                start: '12:45',
                end: '1:15',
                id: 75,
            },
            {
                name: 'SUNAMI',
                start: '1:55',
                end: '2:25',
                id: 76,
            },
            {
                name: 'GWAR',
                start: '3:05',
                end: '3:45',
                id: 77,
            },
            {
                name: 'SUICIDAL TENDENCIES',
                start: '4:55',
                end: '5:55',
                id: 78,
            },
            {
                name: 'ROB ZOMBIE',
                start: '7:05',
                end: '8:10',
                id: 79,
            },
        ],
        'NOFX World': [
            {
                name: 'DOOM SCROLL',
                start: '12:30',
                end: '1:00',
                id: 80,
            },
            {
                name: 'COBRA SKULLS',
                start: '1:30',
                end: '2:00',
                id: 81,
            },
            {
                name: 'SWINGIN UTTERS',
                start: '2:30',
                end: '3:00',
                id: 82,
            },
            {
                name: 'STRUNG OUT',
                start: '3:30',
                end: '4:00',
                id: 83,
            },
            {
                name: 'THE VANDALS',
                start: '4:30',
                end: '5:15',
                id: 84,
            },
            {
                name: 'LAURA JANE GRACE WITH CATBITE',
                start: '5:45',
                end: '6:30',
                id: 85,
            },
            {
                name: 'PENNYWISE',
                start: '7:00',
                end: '8:00',
                id: 86,
            },
            {
                name: 'NOFX: A FINAL FAREWELL',
                start: '8:30',
                end: '10:00',
                id: 87,
            },
        ],
        'Rise Stage': [
            {
                name: 'SAXSQUATCH',
                start: '1:00',
                end: '1:30',
                id: 88,
            },
            {
                name: 'FIDDLEHEAD',
                start: '2:10',
                end: '2:50',
                id: 89,
            },
            {
                name: 'CURSIVE',
                start: '3:30',
                end: '4:10',
                id: 90,
            },
            {
                name: 'TIERRA WHACK',
                start: '5:00',
                end: '5:40',
                id: 91,
            },
            {
                name: 'OLIVER TREE',
                start: '6:50',
                end: '7:50',
                id: 92,
            },
            {
                name: 'SUBLIME',
                start: '9:00',
                end: '10:00',
                id: 93,
            },
        ],
        'Radical Stage': [
            {
                name: 'GAMES WE PLAY',
                start: '1:35',
                end: '2:05',
                id: 94,
            },
            {
                name: 'MAGNOLIA PARK',
                start: '2:55',
                end: '3:25',
                id: 95,
            },
            {
                name: 'SLAUGHTER BEACH, DOG',
                start: '4:15',
                end: '4:55',
                id: 96,
            },
            {
                name: 'SOMETHING CORPORATE',
                start: '5:45',
                end: '6:45',
                id: 97,
            },
            {
                name: 'DR. DOG',
                start: '7:55',
                end: '8:55',
                id: 98,
            },
        ],
    },
}
